name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Версия релиза (например: 1.2.3)'
        required: true
        type: string
permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          git push origin release/${{ github.event.inputs.version }}

      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Release v${{ github.event.inputs.version }}" \
            --body "Автоматический PR для релиза версии ${{ github.event.inputs.version }}. Пожалуйста, проверьте изменения." \
            --base main \
            --head release/${{ github.event.inputs.version }} \
            --repo ${{ github.repository }}
